// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SwapSelection
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidCommandSwapPackageString = "09e96945-c6f5-4016-accb-3e0e1959bf46";
        public const string guidCommandSwapPackageCmdSetString = "92a816fe-90f6-4d55-86e7-fec2684b5a74";
        public const string guidImagesString = "47f95833-2f2a-464d-949b-1c3ac0332f12";
        public static Guid guidCommandSwapPackage = new Guid(guidCommandSwapPackageString);
        public static Guid guidCommandSwapPackageCmdSet = new Guid(guidCommandSwapPackageCmdSetString);
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int MyMenuGroup = 0x1020;
        public const int CommandSwapId = 0x0100;
        public const int bmpPic1 = 0x0001;
    }
}
