// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SwapSelection
{
    static class Vsix
    {
        public const string Id = "cc65354e-e926-4e76-ac83-370537081730";
        public const string Name = "Swap Selection";
        public const string Description = @" Using Multi-Selection to select two pieces of text and then swap them.";
        public const string Language = "en-US";
        public const string Version = "2.1";
        public const string Author = "SSDiver";
        public const string Tags = "Multi Select, Selection, Swap, Switch";
    }
}
